import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../api/http";
import { Sidebar } from "../components/Sidebar";
import { StatsBar } from "../components/StatsBar";
import { parseTags } from "../components/utils";
import { useDebouncedEffect } from "../hooks/useDebouncedEffect";
const words = (text = "") => (text.trim() ? text.trim().split(/\s+/).length : 0);
export function DashboardPage({ token, onLogout }) {
  const [sessions, setSessions] = useState([]); const [selected, setSelected] = useState(null); const [q, setQ] = useState(""); const [activeTag, setActiveTag] = useState(""); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [dark, setDark] = useState(localStorage.getItem("vi_theme") === "dark");
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); localStorage.setItem("vi_theme", dark ? "dark" : "light"); }, [dark]);
  async function loadSessions() { const params = new URLSearchParams(); if (q) params.set("q", q); if (activeTag) params.set("tag", activeTag); if (dateFrom) params.set("from", dateFrom); if (dateTo) params.set("to", dateTo); const data = await apiRequest(`/sessions?${params.toString()}`, {}, token); setSessions(data); if (!selected && data.length) setSelected(data[0]); if (selected) { const fresh = data.find((s) => s._id === selected._id); if (fresh) setSelected(fresh); } }
  useEffect(() => { loadSessions().catch(console.error); }, [activeTag, dateFrom, dateTo]);
  useDebouncedEffect(() => { loadSessions().catch(console.error); }, [q], 300);
  const tags = useMemo(() => { const tagSet = new Set(); sessions.forEach((s) => s.tags?.forEach((t) => tagSet.add(t))); return [...tagSet].sort((a, b) => a.localeCompare(b)); }, [sessions]);
  async function createSession() { const created = await apiRequest("/sessions", { method: "POST", body: JSON.stringify({ title: "New Writing Session", content: "", startTime: new Date().toISOString(), tags: [] }) }, token); setSessions((prev) => [created, ...prev]); setSelected(created); }
  async function saveSession(sessionData) { const updated = await apiRequest(`/sessions/${sessionData._id}`, { method: "PUT", body: JSON.stringify({ ...sessionData, wordCount: words(sessionData.content) }) }, token); setSessions((prev) => prev.map((s) => (s._id === updated._id ? updated : s))); setSelected(updated); }
  useDebouncedEffect(() => { if (!selected?._id) return; saveSession(selected).catch(console.error); }, [selected?.title, selected?.content, selected?.tags?.join(",")], 1200);
  useEffect(() => { if (!selected?._id) return; const timer = setInterval(() => { saveSession({ ...selected, endTime: new Date().toISOString() }).catch(console.error); }, 8000); return () => clearInterval(timer); }, [selected]);
  async function removeSession(id) { await apiRequest(`/sessions/${id}`, { method: "DELETE" }, token); const next = sessions.filter((s) => s._id !== id); setSessions(next); setSelected(next[0] || null); }
  return <div className="min-h-screen bg-stone-100 text-zinc-900 transition-colors dark:bg-zinc-950 dark:text-zinc-100 md:flex"><Sidebar sessions={sessions} selectedId={selected?._id} onSelect={setSelected} onCreate={createSession} tags={tags} activeTag={activeTag} setActiveTag={setActiveTag} q={q} setQ={setQ} /><main className="flex-1 p-4 md:p-8"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} className="rounded border px-2 py-1 dark:border-zinc-700 dark:bg-zinc-900" /><input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} className="rounded border px-2 py-1 dark:border-zinc-700 dark:bg-zinc-900" /></div><div className="flex gap-2"><button className="rounded bg-stone-200 px-3 py-1 text-sm dark:bg-zinc-800" onClick={() => setDark((d) => !d)}>{dark ? "Light" : "Dark"} mode</button><button className="rounded bg-stone-200 px-3 py-1 text-sm dark:bg-zinc-800" onClick={onLogout}>Logout</button></div></div><StatsBar session={selected} />{selected ? <section className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm transition dark:border-zinc-800 dark:bg-zinc-900 md:p-6"><input value={selected.title} onChange={(e) => setSelected((prev) => ({ ...prev, title: e.target.value }))} className="mb-3 w-full border-b border-stone-200 bg-transparent py-2 text-2xl font-semibold outline-none dark:border-zinc-700" /><input value={(selected.tags || []).join(", ")} onChange={(e) => setSelected((prev) => ({ ...prev, tags: parseTags(e.target.value) }))} className="mb-3 w-full rounded-lg border border-stone-200 bg-transparent px-3 py-2 text-sm outline-none dark:border-zinc-700" placeholder="tags, comma separated" /><textarea value={selected.content} onChange={(e) => setSelected((prev) => ({ ...prev, content: e.target.value, wordCount: words(e.target.value), lastEditedAt: new Date().toISOString() }))} placeholder="Start writing..." className="min-h-[55vh] w-full resize-y rounded-xl border border-stone-200 bg-stone-50 p-4 text-base leading-7 outline-none ring-emerald-400 focus:ring dark:border-zinc-700 dark:bg-zinc-950" /><div className="mt-4 flex gap-2"><button onClick={() => saveSession({ ...selected, endTime: new Date().toISOString() })} className="rounded bg-emerald-500 px-3 py-2 text-sm font-semibold text-white">Save now</button><button onClick={() => removeSession(selected._id)} className="rounded bg-red-500 px-3 py-2 text-sm font-semibold text-white">Delete</button></div></section> : <div className="rounded-xl border border-dashed border-stone-300 p-10 text-center text-stone-500 dark:border-zinc-700">Create or select a writing session to begin.</div>}</main></div>;
}
