import { Session } from "../models/Session.js";
const countWords = (text = "") => (text.trim() ? text.trim().split(/\s+/).length : 0);
const sessionDurationSeconds = (startTime, endTime) => Math.max(0, Math.floor(((endTime ? new Date(endTime).getTime() : Date.now()) - new Date(startTime).getTime()) / 1000));
export async function createSession(req, res) { const now = new Date(); const session = await Session.create({ userId: req.userId, title: req.body.title?.trim() || "Untitled Session", content: req.body.content || "", startTime: req.body.startTime || now, endTime: req.body.endTime || null, tags: Array.isArray(req.body.tags) ? req.body.tags : [], wordCount: countWords(req.body.content || ""), duration: sessionDurationSeconds(req.body.startTime || now, req.body.endTime || null), lastEditedAt: now }); return res.status(201).json(session); }
export async function listSessions(req, res) { const { q, tag, from, to } = req.query; const filter = { userId: req.userId }; if (tag) filter.tags = tag; if (from || to) { filter.createdAt = {}; if (from) filter.createdAt.$gte = new Date(from); if (to) filter.createdAt.$lte = new Date(to); } if (q) filter.$or = [{ title: { $regex: q, $options: "i" } }, { content: { $regex: q, $options: "i" } }]; const sessions = await Session.find(filter).sort({ updatedAt: -1 }).lean(); return res.json(sessions); }
export async function getSession(req, res) { const session = await Session.findOne({ _id: req.params.id, userId: req.userId }); if (!session) return res.status(404).json({ message: "Session not found" }); return res.json(session); }
export async function updateSession(req, res) { const existing = await Session.findOne({ _id: req.params.id, userId: req.userId }); if (!existing) return res.status(404).json({ message: "Session not found" }); const nextContent = req.body.content ?? existing.content; const nextStart = req.body.startTime ?? existing.startTime; const nextEnd = req.body.endTime ?? existing.endTime; existing.title = req.body.title?.trim() || existing.title; existing.content = nextContent; existing.tags = Array.isArray(req.body.tags) ? req.body.tags : existing.tags; existing.startTime = nextStart; existing.endTime = nextEnd; existing.wordCount = countWords(nextContent); existing.duration = sessionDurationSeconds(nextStart, nextEnd); existing.lastEditedAt = new Date(); await existing.save(); return res.json(existing); }
export async function deleteSession(req, res) { const deleted = await Session.findOneAndDelete({ _id: req.params.id, userId: req.userId }); if (!deleted) return res.status(404).json({ message: "Session not found" }); return res.status(204).send(); }
export async function listTags(req, res) { const tags = await Session.distinct("tags", { userId: req.userId }); return res.json(tags.filter(Boolean).sort((a, b) => a.localeCompare(b))); }
